version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/packages/app"
    schedule:
      interval: weekly
  - package-ecosystem: npm
    directory: "/packages/cdn"
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
